name: Feedback Report
description: Submit your feedback or suggestions.
title: "[Feedback]: "
labels: ["feedback"]
projects: ["feedbacks"]
assignees: []
body:
  - type: textarea
    id: feedback
    attributes:
      label: Feedback
      description: Provide your feedback or suggestion.
      placeholder: Describe your feedback here.
      value: "Your feedback here."
    validations:
      required: true
  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: What is the impact of this feedback?
      options:
        - Low
        - Medium
        - High (Default)
      default: 2
    validations:
      required: true