name: Meeting Agenda
description: Plan the agenda for an upcoming meeting.
title: "[Agenda]: "
labels: ["agenda"]
projects: ["meetings"]
assignees:
  - SampleAssignee
body:
  - type: input
    id: date
    attributes:
      label: Meeting Date
      description: Date of the meeting.
      placeholder: ex. YYYY-MM-DD
    validations:
      required: true
  - type: textarea
    id: topics
    attributes:
      label: Agenda Topics
      description: List the topics that will be discussed during the meeting.
      placeholder: List the topics here.
      value: "Topic 1: ...\nTopic 2: ..."
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other relevant information or instructions for the meeting.
      placeholder: Include any additional details here.
      value: "Additional information here."
    validations:
      required: false