name: Bug Report
description: Report a bug.
title: "[Bug]: "
labels: ["bugs"]
projects: []
assignees:
  - SampleAssignee
body:
  - type: textarea
    id: description
    attributes:
      label: bug Description
      description: Describe the bug in detail.
      placeholder: Describe the bug here.
      value: "An bug occurred."
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this bug?
      options:
        - Low
        - Medium
        - High (Default)
      default: 2
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: In which environment does this issue occur?
      options:
        - Development
        - Staging
        - Production (Default)
      default: 2
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide steps to reproduce the issue.
      placeholder: Step-by-step instructions.
      value: "Step 1: ..."
    validations:
      required: true
