name: Feature Request
description: Submit a request for a new feature or enhancement.
title: "[Feature Request]: "
labels: ["feature"]
projects: ["24-S2-2-C-EduKATE/4"]
assignees:
  - SampleAssignee
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature or enhancement you are requesting.
      placeholder: Describe the feature here.
      value: "Feature description here."
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low
        - Medium
        - High (Default)
      default: 2
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How will this feature be used or why is it needed?
      placeholder: Describe the use case here.
      value: "Use case description here."
