name: Reflection Report
description: Share your reflections and insights.
title: "[Reflection]: "
labels: ["reflection"]
projects: ["24-S2-2-C-EduKATE/7"]
assignees:
  - SampleAssignee
body:
  - type: textarea
    id: reflection
    attributes:
      label: Reflection
      description: Share your insights or observations.
      placeholder: Describe your reflections here.
      value: "Your reflections here."