name: Risk Report
description: Report a potential risk to the project.
title: "[Risk]: "
labels: ["risk"]
projects: ["risks"]
assignees:
  - SampleAssignee
body:
  - type: textarea
    id: description
    attributes:
      label: Risk Description
      description: Describe the potential risk.
      placeholder: Describe the risk here.
      value: "A potential risk was identified."
  - type: dropdown
    id: likelihood
    attributes:
      label: Likelihood
      description: How likely is this risk to occur?
      options:
        - Low
        - Medium
        - High (Default)
      default: 2
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: What is the potential impact of this risk?
      options:
        - Minor
        - Moderate
        - Critical (Default)
      default: 2