name: setup-node
description: "Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js ⚙️
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Cache dependencies ⚡
      working-directory: ./landing page
      id: cache_dependencies
      uses: actions/cache@v3
      with:
        path: ./landing page/node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies 🔧
      working-directory: ./landing page
      shell: bash
      if: steps.cache_dependencies.outputs.cache-hit != 'true'
      run: npm ci